import { ProjectCard } from "@/components/project-card";
import { SectionHeader } from "@/components/section-header";

import image_duff_intelligence from "@/public/featured_projects/duff-intelligence.webp";
import image_forgr from "@/public/featured_projects/forgr.webp";
import image_extra_mile_valley from "@/public/featured_projects/extra-mile-valley.webp";
import image_patchmentation from "@/public/featured_projects/patchmentation.webp";
import image_deep_face_drawing from "@/public/featured_projects/deep-face-drawing.webp";
import image_grayscale_face_colorization from "@/public/featured_projects/grayscale-face-colorization.webp";
import imgae_fiftyone_plotly_dash from "@/public/featured_projects/fiftyone-plotly-dash.webp";
import image_person_face_dataset from "@/public/featured_projects/person-face-dataset.webp";
import image_person_face_sketches_dataset from "@/public/featured_projects/person-face-sketches-dataset.webp";

const DUMMY_PROJECTS = [
  {
    title: "Duff Intelligence with MCP",
    description:
      "An AI revenue intelligence copilot with MCP integrations that helps sports venue owners make smarter business decisions.",
    tags: ["AI", "MCP", "Next.js", "Kotlin"],
    href: "https://duffpadel.com/",
    image: image_duff_intelligence,
  },
  {
    title: "Extra Mile Valley: Interactive Learning Gamification",
    description:
      "A web-based gamification platform designed to immerse employees in company values through interactive gameplay.",
    tags: ["Next.js", "Tailwind CSS", "Java", "Spring Boot"],
    image: image_extra_mile_valley,
  },
  {
    title: "Forgr: Online Store Builder",
    description:
      "A direct selling platform that lets brands launch their own storefront, own their customers, and sell without marketplace commissions.",
    tags: ["Next.js", "Kotlin", "Commerce", "QRIS"],
    image: image_forgr,
  },
  {
    title: "Patchmentation: A Python Library for Patch Augmentation",
    description:
      "Patch augmentation is data augmentation technique that synthesizes training images by combining objects from multiple images into different backgrounds.",
    tags: ["Python", "Computer Vision", "Data Augmentation"],
    href: "https://pypi.org/project/patchmentation/",
    image: image_patchmentation,
  },
  {
    title: "DeepFaceDrawing: Deep Generation of Face Images from Sketches",
    description:
      "A complete implementation of DeepFaceDrawing with a two-stage training pipeline, CLI inference, Docker deployment, and a web interface.",
    tags: ["Python", "Computer Vision", "Generative AI"],
    href: "https://github.com/Xu-Justin/DeepFaceDrawing",
    image: image_deep_face_drawing,
  },
  {
    title: "Grayscale Face Image Colorization",
    description:
      "A generative model that colorizes grayscale face images into realistic, full-color portraits.",
    tags: ["Python", "Computer Vision", "Generative AI"],
    href: "https://github.com/Xu-Justin/DeepFaceDrawing",
    image: image_grayscale_face_colorization,
  },
  {
    title: "FiftyOne Embeddings Visualization",
    description:
      "An interactive dashboard for exploring computer vision embeddings and visually analyzing image similarity using FiftyOne and Plotly Dash.",
    tags: ["Python", "FiftyOne", "Plotly Dash"],
    href: "https://github.com/Xu-Justin/fiftyone-plotly-dash",
    image: imgae_fiftyone_plotly_dash,
  },
  {
    title: "Person Face Dataset",
    description:
      "A dataset with 10K images of person face generated by thispersondoesnotexist.",
    tags: ["Kaggle", "Dataset", "Computer Vision"],
    href: "https://www.kaggle.com/datasets/almightyj/person-face-dataset-thispersondoesnotexist",
    image: image_person_face_dataset,
  },
  {
    title: "Person Face Sketches Dataset",
    description:
      "A dataset with 21K+ images pair of person face photos and sketches.",
    tags: ["Kaggle", "Dataset", "Computer Vision"],
    href: "https://www.kaggle.com/datasets/almightyj/person-face-sketches",
    image: image_person_face_sketches_dataset,
  },
];

export function ProjectsSection() {
  return (
    <section id="projects" className="flex flex-col items-center justify-start w-full py-16 sm:py-24 px-6 md:px-16 lg:px-24">
      <div className="flex flex-col gap-12 sm:gap-16 w-full max-w-400">
        <SectionHeader
          label="// My Work"
          title="Featured Projects"
          subtitle="These are some of my favorite things I've built so far. Each one represents a challenge, a lesson, and a chance to turn ideas into products and something meaningful."
        />

        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {DUMMY_PROJECTS.map((project) => (
            <ProjectCard key={project.title} {...project} />
          ))}
        </div>
      </div>
    </section>
  );
}
